# Generated by Django 3.2.5 on 2021-07-13 15:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famous_ghazals',
            name='shayari',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ghazals_home',
            name='shayari',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new_ghazals',
            name='shayari',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
