# Generated by Django 3.2.5 on 2021-07-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabd', '0003_auto_20210715_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_ghazals',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
